version: "3"
services:
  weblate:
    image: weblate/weblate
    volumes:
      - /mnt/Data/weblate/containers-data/weblate:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:12-alpine
    env_file:
      - ./environment
    volumes:
      - /mnt/Data/weblate/containers-data/pg:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /mnt/Data/weblate/containers-data/redis:/data
#volumes:
#  weblate-data: {}
#  postgres-data: {}
#  redis-data: {}
